image: ghcr.io/siemens/kas/kas

  # First do a common bootstrap, and then build all the targets
stages:
  - prep
  - bootstrap
  - build

# Common job fragment to get a worker ready
.setup:
  stage: build
  variables:
    KAS_WORK_DIR: $CI_PROJECT_DIR/work
    KAS_REPO_REF_DIR: $CI_BUILDS_DIR/persist/repos
    SSTATE_DIR: $CI_BUILDS_DIR/persist/sstate
    DL_DIR: $CI_BUILDS_DIR/persist/downloads
    BB_LOGCONFIG: $CI_PROJECT_DIR/ci/logging.yml
  before_script:
    - echo KAS_WORK_DIR = $KAS_WORK_DIR
    - echo SSTATE_DIR = $SSTATE_DIR
    - echo DL_DIR = $DL_DIR
    - rm -rf $KAS_WORK_DIR
    - mkdir --verbose --parents $KAS_WORK_DIR $KAS_REPO_REF_DIR $SSTATE_DIR $DL_DIR

# Generalised fragment to do a Kas build
.build:
  extends: .setup
  script:
  - KASFILES=$(ci/jobs-to-kas $CI_JOB_NAME)
  - kas shell --update --force-checkout $KASFILES -c 'cat conf/*.conf'
  - kas build $KASFILES
  - ./ci/check-warnings $KAS_WORK_DIR/build/warnings.log


#
# Prep stage, update repositories once
#
update-repos:
  extends: .setup
  stage: prep
  script:
  - flock --verbose --timeout 60 $KAS_REPO_REF_DIR ./ci/update-repos


#
# Bootstrap stage, bootstrap and machine coverage
#

# Build a number of native tools first to ensure the other builders don't race
# over them
n1sdp/bootstrap:
  extends: .build
  stage: bootstrap

# What percentage of machines in the layer do we build
machine-coverage:
  stage: bootstrap
  script:
  - ./ci/check-machine-coverage
  coverage: '/Coverage: \d+/'


#
# Build stage, the actual build jobs
#

a5ds:
  extends: .build

foundation-armv8:
  extends: .build

fvp-base:
  extends: .build

gem5-arm64:
  extends: .build

juno:
  extends: .build

juno/musl:
  extends: .build

n1sdp:
  extends: .build

n1sdp/armgcc:
  extends: .build

qemuarm:
  extends: .build

qemuarmv5:
  extends: .build

tc0:
  extends: .build


#
# Utility tasks, not executed automatically
#

delete-dl-dir:
  extends: .setup
  stage: prep
  when: manual
  script:
  - rm -rf $DL_DIR/*

delete-repo-dir:
  extends: .setup
  stage: prep
  when: manual
  script:
  - rm -rf $KAS_REPO_REF_DIR/*

# Delete all sstate
delete-sstate:
  extends: .setup
  stage: prep
  when: manual
  script:
  - rm -rf $SSTATE_DIR/*

# Wipe out old sstate
prune-sstate:
  extends: .setup
  stage: prep
  when: manual
  script:
  - du -h -s $SSTATE_DIR
  - find $SSTATE_DIR -type f -atime +30 -delete
  - du -h -s $SSTATE_DIR

# Report on disk usage
usage:
  extends: .setup
  stage: prep
  when: manual
  script:
  - du -h -s $DL_DIR $SSTATE_DIR $KAS_REPO_REF_DIR
